#! /bin/bash

#-------------------------------------------------------------
# Set environment.
LOCALDIR=/datax/users/eenriquez/L-band_analysis/
SPIDEROUT=$LOCALDIR/`hostname`.spider2.local.out.`date "+%s"`

if [ ! -d "$LOCALDIR" ]; then
  mkdir $LOCALDIR
fi
if [ ! -d "$LOCALDIR/logs" ]; then
  mkdir $LOCALDIR/logs
fi
if [ ! -d "$LOCALDIR/stars_out" ]; then
  mkdir $LOCALDIR/stars_out
fi

chmod 777 $LOCALDIR
chmod 777 $LOCALDIR/logs
chmod 777 $LOCALDIR/stars_out

cd $LOCALDIR

#-------------------------------------------------------------
#Find data and pairs.

/home/eenriquez/software/Lband_seti/spider2.local >& $SPIDEROUT

/home/eenriquez/software/Lband_seti/find_pairs.py $SPIDEROUT L >& $LOCALDIR/logs/find_pairs.out.`date "+%s"`


