#! /bin/bash

#-------------------------------------------------------------
#activate python environment FTW.
. /opt/pyve/activate woodpy

#-------------------------------------------------------------
# Set environment.
LOCALDIR=/datax/users/wood
PYVEROOT=/opt/pyve/woodpy/norwegian/
SPIDEROUT=$LOCALDIR/`hostname`.spider2.local.out.`date "+%s"`

if [ ! -d "$LOCALDIR" ]; then
  mkdir $LOCALDIR
fi
if [ ! -d "$LOCALDIR/logs" ]; then
  mkdir $LOCALDIR/logs
fi
if [ ! -d "$LOCALDIR/stars_out" ]; then
  mkdir $LOCALDIR/stars_out
fi

chmod 777 $LOCALDIR
chmod 777 $LOCALDIR/logs
chmod 777 $LOCALDIR/stars_out

cd $LOCALDIR

#-------------------------------------------------------------
#mc'ing all output data and logs
export EXTRA=-v0.2
export MC_DIR=wood/nw-output$EXTRA/

#-------------------------------------------------------------

$PYVEROOT/wood_crafting/data_process/spider2.local >& $SPIDEROUT

$PYVEROOT/wood_crafting/data_process/find_pairs.py $SPIDEROUT L  $MC_DIR >& $LOCALDIR/logs/find_pairs.out.`date "+%s"`


