#! /bin/bash

#-------------------------------------------------------------
# Set environment.

LOCALDIR=/datax/users/eenriquez/L-band_analysis
cd $LOCALDIR

#-------------------------------------------------------------

date
echo "$HOSTNAME: Stats."
echo "Targets:" && wc -l $LOCALDIR/L_band_t*
echo "Processed:" && wc -l $LOCALDIR/L_band_p*
echo "Failed:" && wc -l $LOCALDIR/L_band_f*
echo "H5s left over:" && ls $LOCALDIR/stars_out/*h5 | wc -l


