#! /bin/bash

#-------------------------------------------------------------
# Set environment.
LOCALDIR=/datax/users/eenriquez/L-band_analysis/

cd $LOCALDIR

#-------------------------------------------------------------
#Start pipeline

python /home/eenriquez/software/Lband_seti/L-band_seti_pipeline.py

echo "$HOSTNAME: Pipeline run done."
