#! /bin/bash

#-------------------------------------------------------------
# Set environment.
source $HOME/.bash_profile

LOCALDIR=/datax/users/eenriquez/L-band_analysis/
cd $LOCALDIR

node=$1

#-------------------------------------------------------------
#Start pipeline

python /home/eenriquez/software/Lband_seti/L-band_seti_pipeline.py -n $node

echo "$HOSTNAME: Pipeline run done."
